# Use the official MySQL image from Docker Hub
FROM mysql:latest

# Environment variables for MySQL configuration
ENV MYSQL_ROOT_PASSWORD=""
ENV MYSQL_DATABASE=app_db
ENV MYSQL_USER=app_user
ENV MYSQL_PASSWORD="123"
ENV MYSQL_NAME=""
ENV MYSQL_HOST=""
ENV MYSQL_PORT=""


# Expose port 3306 for MySQL connections
EXPOSE ${MYSQL_PORT}

# Set the data directory as a volume
VOLUME /var/lib/mysql
